### ISSUE TITLE
Erro ao executar 

### ISSUE THREAD

**Issue by joneslisboa** [duarteguilherme/consulta_cnpj#1]
Ola, amigo, ao executar seu código o mesmo apresenta esse erro, poderia por gentileza me dar uma luz ?? 

>>> print(x.consulta_cnpj('60701190000104'))
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    print(x.consulta_cnpj('60701190000104'))
  File "C:\Users\jones\Desktop\python\consulta_cnpj-master-py\consulta_cnpj-master\consulta_cnpj.py", line 104, in consulta_cnpj
    captcha = self.baixa_captcha()
  File "C:\Users\jones\Desktop\python\consulta_cnpj-master-py\consulta_cnpj-master\consulta_cnpj.py", line 86, in baixa_captcha
    imagem_data = (ndimage.imread('teste.png'))
  File "C:\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python35\lib\site-packages\scipy\ndimage\io.py", line 28, in imread
    return _imread(fname, flatten, mode)
  File "C:\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Python35\lib\site-packages\scipy\misc\pilutil.py", line 164, in imread
    im = Image.open(name)
  File "C:\Python35\lib\site-packages\PIL\Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'teste.png'
>>>

**Comment by joneslisboa** [comment]
Primeiramente obrigado pela atenção e por disponibilizar do seu tempo , sim o arquivo foi criado, estou rodando o python no windows , a permissão da pasta esta ok. 

Desde já agradeço :)

**Comment by joneslisboa** [comment]
Obrigado consegui fazer  funcionar, sem querer abusar como faz para melhorar a assertividade dos captchas ? é possivel ?

**Comment by duarteguilherme** [comment]
Opa, @joneslisboa , até há. Eu vou mexer no modelo depois e deixar mais tempo rodando.

**Comment by CleitonDeLima** [comment]
Tenho o mesmo erro, parece ser o comando curl:  
`curl --tlsv1.0 -k -b cookiefile -c cookiefile <url>`

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.receita.fazenda.gov.br:443
```

Como você resolveu o problema @joneslisboa ?

**Comment by joneslisboa** [comment]
Cleiton 
Acredito que o problema na verdade e com a receita, parece que ficam sobrecarregados e o server deles reseta as conexões, tente por no comando curl um -v pois ai ele te mostra o erro certinho,  só consigo rodar na madrugada, funciona certinho :) tem essa questão, se você precisar de poucas consultas dia tem um monte de api por ai cobram centavinhos por consulta 

Espero por ter ajudado , abs ...

**Comment by ltouro** [comment]
@duarteguilherme Guilherme, alguma chance de disponibilizar o projeto para criação do modelo de captcha? Posso tentar ajudar disponibilizando processamento no Azure para treinar o modelo por mais tempo. Abs

**Comment by Guilhermeslucas** [comment]
Estou trabalhando em um PR para incluir um arquivo de ```requirements.txt``` e estou tendo problemas para rodar o exemplo. O traceback do problema é o seguinte:
```
Traceback (most recent call last):
  File "teste.py", line 3, in <module>
    print(x.consulta_cnpj('60701190000104'))
  File "/mnt/c/Users/guilhermelcs/Documents/Repos/consulta_cnpj/consulta_cnpj.py", line 108, in consulta_cnpj
    link_dados  = 'https://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/' + BeautifulSoup(pagina_validacao, "html.parser").find('a')['href'].strip()
```
Alguém mais com esse problema? Abraços!

**Comment by Guilhermeslucas** [comment]
Essa issue acontece quando você tenta rodar o teste com um CNPJ inválido, que é o caso da que está no exemplo. Ao colocar um CNPJ válido, tudo funciona normalmente! Abraços!

**Comment by cuducos** [comment]
Oi @joneslisboa,

Caí no mesmo erro… investigando aqui descobri que o `curl` está falhando:

```sh
# curl --tlsv1.0 -k -b cookiefile -c cookiefile https://www.receita.fazenda.gov.br/PessoaJuridica/CNPJ/cnpjreva/captcha/gerarCaptcha.asp
curl: (35) Unknown SSL protocol error in connection to www.receita.fazenda.gov.br:443
```

Com isso o resultado de `self.sessao.get(url)` é vazio (`b''`) e portanto a imagem não é um PNG válido. Ainda não sei como contornar, mas só compartilhando.

**Comment by joneslisboa** [comment]
Ola Depois de apanhar muito descobri que esse erro e causado pela versão do curl ou do openssl que não possui o suporte pra conexão tls1 da receita, alem da instabilidade constante do site da receita  experimente usar o url sem o https , pra mim aqui funcionou, estou usando somente a parte da decodificação, o restante estou fazendo com php mesmo , e um pouco mais lento mas nao falha. 
Se eu puder ajudar em algo , só pedir.

**Comment by cuducos** [comment]
> descobri que esse erro e causado pela versão do curl ou do openssl

Você pode confirmar quais versões está usando?

**Comment by joneslisboa** [comment]
Opa claro segue, estou usando um vps na ovh  com centos 7.0 

[root@vps197922 ~]# curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.34 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
[root@vps197922 ~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by legalindo** [comment]
![Capturar](https://user-images.githubusercontent.com/47422271/60130936-985ded80-976e-11e9-8288-b9012b814cfe.PNG)
Não estou conseguindo rodar, esta aparecendo o seguinte erro:
" PermissionError: [Errno 13] Permission denied: 'C:\\Users\\LGALME~1\\AppData\\Local\\Temp\\tmpwpay30pg.png'", conforme imagem em anexo. Alguem poderia me ajudar??
